# Generated by Django 4.1.6 on 2023-02-04 15:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("social", "0003_tweet"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="email",
            field=models.EmailField(
                default="email@email.com", max_length=254, verbose_name="User Email"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="first_name",
            field=models.CharField(default="first_name", max_length=50),
        ),
        migrations.AddField(
            model_name="profile",
            name="last_name",
            field=models.CharField(default="last_name", max_length=50),
        ),
    ]
