# Generated by Django 4.1.6 on 2023-02-04 15:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("social", "0004_profile_email_profile_first_name_profile_last_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="email",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="last_name",
        ),
    ]
